import dash_html_components as html

# REPORT TEXT

INTRO_P1 = html.P(['The WiCS Advocacy Survey Report aims to assess the experiences of undergraduate students with computer science at Harvard, particularly as they relate to gender, ethnicity, and other aspects of identity. In the Fall of 2020, we surveyed over three hundred undergraduate students who were currently enrolled in Harvard College from all disciplines and backgrounds. The survey included questions relating to prior technical experiences, academic engagement, post-graduate opportunities, community involvement, discrimination, and representation.'])
INTRO_P2 = html.P(['Our work builds off of the ', html.A('2015 WiCS Advocacy Survey Report', href='http://advocacy.harvardwics.com/data/', target='_blank'), ', our organization’s first attempt to study gender inequity within computer science on campus through surveying the student population. While many aspects of diversity and inclusion in computer science at Harvard have improved over the past five years, our report illustrates that there is still much progress to be made, especially in considering the ways that intersecting aspects of identity can have profound effects on student experiences within the field. We hope that the findings from this report can help shape effective diversity initiatives within the Harvard CS department, as well as provide a valuable foundation for future research surrounding these issues.'])
INTRO_P3 = html.P(['Authors: Cassandra Kane ’21 (Lead), Iman Alshawk ’23, Alyssa Huang ’24, Karen Li ’24, Michelle Lin ’24, Diana Zhu ’23'], style={'font-style' : 'italic'})

ABOUT_P1 = html.P(['The 2020 WiCS Advocacy Survey gathered over three hundred responses from Harvard College students who were enrolled during the Fall 2020 semester. The survey was released through Qualtrics on October 20th, 2020 and closed on October 31st, 2020. Students received ', html.A('individualized links', href='https://www.qualtrics.com/support/survey-platform/distributions-module/email-distribution/emails-overview/#UnderstandingTheIndividualLink', target='_blank'), ' to the survey through their Harvard College email address and could therefore only complete the survey once. All survey responses were then ', html.A('automatically anonymized', href='https://www.qualtrics.com/support/survey-platform/survey-module/survey-options/survey-termination/#AnonymizingResponses', target='_blank'), ' through Qualtrics upon submission. The survey was also publicized over Harvard College email lists and forums. As part of our promotional efforts, WiCS donated $1 for every survey response, with the donation split between ', html.A('Black Girls Code', href='https://www.blackgirlscode.com/', target='_blank'), ', ', html.A('Out in Tech', href='https://outintech.com/', target='_blank'), ', and ', html.A('Code2040', href='http://www.code2040.org/', target='_blank'), '. The distribution of the 2020 WiCS Advocacy Survey was also aided by SEAS.'])
ABOUT_P2 = html.P(['To preserve the privacy of the respondents, data analysis is omitted if the number of respondents within a demographic category (or within a given intersection of demographic categories) is less than five. Filtering functionality is limited to two demographic filters at a time to preserve respondent privacy as well. Raw, anonymized survey responses have only been viewed and managed by the WiCS Advocacy Survey Report team. Results are considered significant if the calculated p-value from a z-score test for two population proportions is less than 0.05.'])
ABOUT_KEY_TERMS = html.Div([
	html.P(['Key Terms'], style={'font-weight' : 'bold'}),
	html.Div([
		html.P([html.Strong('CS:'), ' Computer Science'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('SEAS:'), ' Harvard John A. Paulson School of Engineering and Applied Sciences'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('WiCS:'), ' Harvard Women in Computer Science'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('Non-male:'), ' identifying as female, non-binary, third gender, agender, or genderqueer'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('Male:'), ' identifying as male'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('URM:'), ' underrepresented minority, i.e. identifying as Black / African American, Hispanic / Latinx, or American Indian / Alaskan Native'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('Non-URM:'), ' ', html.A('non-underrepresented minority', href='https://www.nacme.org/underrepresented-minorities', target='_blank'), ', i.e. identifying as White or Asian'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('BGLTQ+:'), ' identifying as bisexual, gay, lesbian, transgender, or queer'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('Non-BGLTQ+:'), ' identifying as heterosexual and cisgender'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('FGLI:'), ' identifying as first-generation or from a low-income background'], style={'margin-bottom' : '0px'}),
		html.P([html.Strong('Non-FGLI:'), ' not identifying as first-generation and not identifying from a low-income background'], style={'margin-bottom' : '0px'})
	])
])

BACKGROUND_P1 = html.P(['In order to understand students’ current experiences with CS at Harvard, it is critical to understand their experiences with CS before they began college, particularly given ', html.A('known inequalities', href='https://services.google.com/fh/files/misc/diversity-gaps-in-computer-science-report.pdf', target='_blank'), ' in early CS education and exposure.'])
BACKGROUND_P2 = html.P(['The majority of undergraduate students with prior programming or CS experience were exposed to programming or CS in high school. Our survey found no significant differences between male and non-male undergraduate students (nor between male and non-male CS concentrators) in terms of when they were first exposed to computer science, a development since ', html.A('the 2015 report', href='http://advocacy.harvardwics.com/data/', target='_blank'), ' which found that non-male CS concentrators possessed fewer years of programming experience compared to male CS concentrators.'])
BACKGROUND_P3 = html.P(['However, our survey found that URM undergraduates (9.3%) were significantly less likely to be exposed to programming or CS before high school compared to non-URM undergraduates (23.1%). This discrepancy was also evident among CS concentrators specifically.'])

ACADEMICS_P1 = html.P(['Academics are central to the CS experience at Harvard. The following section examines students’ experiences within the classroom, as influenced by course resources, staff support, and student networks.'])
ACADEMICS_P2 = html.P(['Since 2015, there has been significant progress in reducing the gender gap in CS courses at Harvard. According to ', html.A('the 2015 report', href='http://advocacy.harvardwics.com/data/', target='_blank'), ', none of the CS course categories saw a female enrollment above 40%, with the exception of CS20 (Discrete Mathematics for Computer Science) and courses within the 17x track (graphics/visualization/user interfaces). In Fall 2020, based on our survey results (not full course enrollment data), four out of the six course categories show more than 50% non-male enrollment. Moreover, among CS 0xx courses (undergraduate-level introductory courses other than CS50, CS51, and C61), there were significantly more non-male students (72%) than male students (28%) who had taken at least one course within that grouping. However, CS2xx courses (graduate-level courses) still lacked adequate gender representation in enrollment, where male undergraduate enrollment (65%) was significantly higher than non-male undergraduate enrollment (35%).'])
ACADEMICS_P3 = html.P(['In terms of race and ethnicity, the introductory CS courses (CS0xx) yielded no significant differences in enrollment between URM students and non-URM students. However, a significant difference in enrollment between URM students (15%) and non-URM students (85%) exists within the CS1xx courses (standard undergraduate-level courses) and between URM students (10%) and non-URM students (90%) within CS2xx courses (graduate-level courses).'])
ACADEMICS_P4 = html.P(['Overall, gender and racial representation within the introductory courses’ enrollment have improved, indicating that ', html.A('initiatives spearheaded by SEAS', href='https://www.seas.harvard.edu/office-diversity-inclusion-and-belonging/about-us', target='_blank'), ' to bring more non-male and URM students into introductory CS courses have been successful. However, significant gaps still remain in the enrollment for more advanced CS courses.'])
ACADEMICS_P5 = html.P(['The gender gap in perceived abilities for various CS topics has decreased overall since 2015. ', html.A('The 2015 report', href='http://advocacy.harvardwics.com/data/', target='_blank'), ' illustrates that for both programming and CS theory, male students tended to rate themselves average or above average in skill level compared to their peers, while female students tended to rate themselves as average or below average in skill level compared to their peers. Our report shows no significant differences in confidence level between male and non-male CS concentrators for all CS topics except artificial intelligence, where non-male CS concentrators (52.5%) were significantly more likely to evaluate themselves as less knowledgeable to some extent compared to male CS concentrators (30.3%). However, a greater proportion of non-male CS concentrators evaluated themselves to be less knowledgeable to some extent of every CS topic (except graphics/visualization/user interfaces) compared to evaluations from male CS concentrators, even if this difference was minimal.'])
ACADEMICS_P6 = html.P(['For the majority of CS topics presented (computer programming, theoretical CS, economics/computation, graphics/visualization/UI, and artificial intelligence) URM CS concentrators were significantly more likely to evaluate themselves as less knowledgeable to some extent compared to non-URM CS concentrators. Similarly, for four of the CS topics presented (computer programming, theoretical CS, economics/computation, and networks), FGLI CS concentrators were significantly more likely to evaluate themselves as less knowledgeable to some extent compared to non-FGLI CS concentrators. With regard to both race/ethnicity and FGLI status, discrepancies in perceived ability were the most striking for the topics of computer programming, theoretical computer science, and economics/computation.'])
ACADEMICS_P7 = html.P(['Non-male CS concentrators (64.9%) were significantly more likely to disagree to some extent that they would feel comfortable asking or answering questions in lecture compared to male CS concentrators (23.3%). By contrast, there were no significant differences between the comfort levels of male and non-male CS concentrators towards participating in section, asking questions in an online forum, or privately asking the teaching staff questions, with a vast majority of CS concentrators agreeing that they would feel comfortable to some extent with these methods.'])
ACADEMICS_P8 = html.P(['There were no significant differences found between male and non-male students in terms of how easily they could find problem set partners in a CS course, a notable improvement from ', html.A('the 2015 report', href='http://advocacy.harvardwics.com/data/', target='_blank'), ' which found that female students experienced more difficulties finding problem set partners than male students. However, the majority of URM students who had taken a CS course disagreed to some extent that they could easily find problem set partners in a CS course, while the majority of non-URM students agreed to some extent that they could easily find problem set partners.'])
ACADEMICS_P9 = html.P(['Overall, URM students (60.6%) were significantly more likely to disagree to some extent that they could easily find problem set partners in a CS class compared to non-URM students (31.0%). BGLTQ+ (54.3%) and FGLI students (51.6%) were also significantly more likely to disagree to some extent that they could easily find problem set partners in a CS class compared to non-BGLTQ+ (28.4%) and non-FGLI students (28.8%) respectively.'])
ACADEMICS_P10 = html.P(['In general, students felt the most comfortable with consulting with a faculty member about advice for their concentration and the least comfortable with asking for a letter of recommendation, which requires a more personal professor-student connection. Across academic schools, SEAS students (50.5%) were significantly less likely to feel comfortable asking for a letter of recommendation compared to students from other departments (64.1%). SEAS students were also the least comfortable on average compared to students from other schools with asking about career opportunities, research opportunities, and concentration advice. Additionally, CS students were generally less likely to feel comfortable asking for any of the aforementioned support compared to the average Harvard undergraduate.'])

POST_GRAD_P1 = html.P(['Harvard College serves a crucial role in shaping the future career and endeavors of its students. This section focuses on the postgraduate interests and opportunities for current undergraduate students.'])
POST_GRAD_P2 = html.P(['The majority of non-male CS concentrators indicated that they have not considered applying for graduate studies in CS, while the majority of male CS concentrators indicated that they have considered graduate studies in CS but do not intend on applying. Additionally, non-male CS concentrators (37.5%) were significantly more likely to have not considered applying to graduate studies in CS compared to male CS concentrators (15.2%).'])
POST_GRAD_P3 = html.P(['Our results also illustrate that FGLI CS concentrators (50.0%) were significantly more likely to have not considered applying to graduate studies in CS compared to non-FGLI CS concentrators (22.8%). These discrepancies can possibly be attributed to the differences in resources – whether financial or socioeconomic – that are provided to FGLI and non-FGLI students.'])
POST_GRAD_P4 = html.P(['Male CS concentrators (56.7%) were significantly more likely to access direct connections and referrals through close friends and family compared to non-male CS concentrators (29.7%). More drastic discrepancies were evident between FGLI CS concentrators and non-FGLI CS concentrators, where around half of non-FGLI CS concentrators reported being able to find direct connections and referrals through close friends and families while a vast majority of FGLI CS concentrators (92.9%) reported they could not.'])
POST_GRAD_P5 = html.P(['In terms of accessing guidance and mentorship through close friends and family, a less severe discrepancy was reported between male CS concentrators and non-male CS concentrators. However, significant discrepancies still persisted between FGLI CS concentrators (35.7%) and non-FGLI concentrators (68.6%) when accessing guidance and mentorship through close friends and family, in line with access to direct connections and referrals. General career resources that proved to be more equally accessible to CS concentrators from marginalized communities included professional networks, alumni networks, and The Harvard Office of Career Services.'])

DISCRIMINATION_P1 = html.P(['A student’s experience at Harvard is greatly dependent on the support of their concentration department, and whether or not a student experiences discrimination can greatly affect their decision to pursue that field. The following section reveals multiple areas for improvement when combatting discrimination on the basis of gender, race and ethnicity, and sexuality.'])
DISCRIMINATION_P2 = html.P(['In general, the largest discrepancies in student experiences with discrimination stemmed from differences in gender. Our survey found that non-male undergraduates (18.8%) were significantly more likely to agree to some extent that they had experienced discrimination within their primary department on the basis of their gender compared to male undergraduates (1.6%), and this difference was evident to a greater extent among CS concentrators specifically. Across gender, race/ethnicity, and sexuality, these disparities only worsened when measured within the CS department; 65.6% of male CS concentrators strongly disagreed that they had experienced discrimination on the basis of gender within the CS department, while only 10.8% of non-male CS concentrators strongly disagreed. Similarly, 29.5% more non-URM CS concentrators than URM CS concentrators disagreed that they had experienced discrimination within their primary department on the basis of race or ethnicity, in comparison to a 21.5% difference between non-URM and URM decided concentrators in general.'])
DISCRIMINATION_P3 = html.P(['The SEAS Office of Diversity, Inclusion, and Belonging has set goals within their ', html.A('strategic plan', href='https://www.seas.harvard.edu/office-diversity-inclusion-and-belonging/committee-dib/strategic-plan', target='_blank'), ' to “reduce/prevent instances of harassment or discrimination based on any aspect of identity; create clear, easily accessible processes for reporting without fear of retaliation.” While the advertisement of information related to Title IX, BLGTQ, Student Life, and other diversity focused resources is an immediate goal, the other steps outlined such as creating bias and harassment reporting systems and annual bystander intervention training are medium-term goals that are expected to be implemented in the coming few years.'])
DISCRIMINATION_P4 = html.P(['Overall, CS concentrators were more likely to agree to some extent that gender discrimination was an issue within their deparatment compared to students across all concentrations. For instance, while 35.3% of non-male students agreed to some extent that gender discrimination was an issue within their concentration department, 64.8% of non-male CS concentrators agreed to some extent that gender discrimination was an issue within the CS department.'])
DISCRIMINATION_P5 = html.P(['Perceptions of racial discrimination within their department also differed significantly between CS concentrators and all concentrators. While 10.2% of Black or African American students overall strongly agreed that discrimination on the basis of race/ethnicity was an issue within their department, 23.1% of Black or African American CS concentrators strongly agreed that racial discrimination was an issue within the CS department. Similarly, Hispanic or Latinx CS concentrators (80%) were significantly more likely to agree to some extent that discrimination on the basis of race/ethnicity was an issue within their department compared to Hispanic or Latinx concentrators from all departments (28.1%).'])

BELONGING_P1 = html.P(['This final section focuses on belonging, delving into whether students feel represented within their concentration department and how students can best be supported by their teaching staff and peers.'])
BELONGING_P2 = html.P(['Among all schools, 61.2% of non-male students agreed to any extent that the aspects of their identity that are important to them were represented among the students in their primary concentration department, while only 45.45% of non-male SEAS concentrators felt that their identities were represented among the students in their primary concentration department. Within this group, only 5.5% of non-male SEAS concentrators strongly agreed that their identities felt represented, and among CS concentrators specifically, only 2.7% of non-male students strongly agreed.'])
BELONGING_P3 = html.P(['There was a strikingly high percentage (46.2%) of Black or African American students at Harvard who disagreed to some extent that the aspects of their identity that are important to them were represented among the students in their primary department. Within the CS department, 61.5% of Black or African American CS concentrators and 60% of Hispanic or Latinx CS concentrators felt that the important aspects of their identity were not represented within the department, differing significantly from the 25.8% of Asian CS concentrators and 23.1% of white CS concentrators who did not feel that the important aspects of their identity were adequately represented. Additionally, No FGLI CS concentrators indicated that they agreed or strongly agreed with the statement that the important aspects of their identity were represented within their concentration department, as opposed to 45.1% of non-FGLI CS students who agreed or strongly agreed.'])
BELONGING_P4 = html.P(['In regards to students’ sense of representation among the teaching staff for courses in their primary concentration, similar trends were evident but oftentimes more extreme. Within the CS department, it is clear that Black or African American and Hispanic or Latinx students felt greatly underrepresented among the teaching staff for their courses—no Hispanic or Latinx CS concentrators agreed to any extent that they felt that the important aspects of their identity were represented, and 69.2% of Black or African American CS concentrators disagreed to some extent that they felt represented. The SEAS Office of Diversity, Inclusion, and Belonging has ', html.A('created extensive targets', href='https://www.seas.harvard.edu/office-diversity-inclusion-and-belonging/committee-dib/strategic-plan', target='_blank'), ' to recruit diverse faculty and staff with special attention given to increasing the number of females and underrepresented minorities within the SEAS community, but these changes have yet to be reflected in student body sentiments.'])
BELONGING_P5 = html.P(['The majority of CS concentrators agreed to some extent that the CS department is academically, professionally, and emotionally supportive, with minimal discrepancies between male and non-male CS concentrators. However, although a majority of CS concentrators also agreed to some extent that the CS department is welcoming and inclusive, significantly more male CS concentrators (53.3%) either agreed or strongly agreed that the CS department is welcoming and inclusive compared to non-male CS concentrators (24.3%). This discrepancy between male and non-male CS concentrators was less severe when asked whether the student community within the CS department is welcoming and inclusive, though still present.'])
BELONGING_P6 = html.P(['Additionally, when asked whether their primary concentration department is academically supportive, professionally supportive, emotionally supportive, and welcoming/inclusive, SEAS concentrators were the most likely to disagree to some extent with these statements among all of the schools. However, the same was not true of the student communities within these schools.'])

CONCLUSION_P1 = html.P(['Work in progress...'])
CONCLUSION_P2 = html.P(['We would like to thank Alexis Stokes, Beth Musser, Christina Zaldaña, Joanne Kang, Stephen Chong, and Adam Hesterberg for their guidance through the development of this report. We would also like to thank the WiCS community, alongside all of the Harvard College student organizations that work tirelessly to promote equity and inclusion on campus and beyond.'])
